FROM golang:1.25-alpine AS builder

RUN apk add --no-cache curl bash

WORKDIR /app

COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o /api ./cmd/api/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /api ./api
EXPOSE 8080
CMD ["/app/api"]
